### ISSUE TITLE
components of flux vector and flux offsets in Flux control instrument should be parameters

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#102]
Currently the flux vector and flux offsets are vectors. 
They should be parameters for the following reason 
- Easier for printing and data extraction 
- More clear for control 

The change should not break anything. Writing down here as a todo

**Comment by AdriaanRol** [comment]
Also found that the units in the flux control are wrong (mV vs V)

**Comment by AdriaanRol** [comment]
This has been implemented for the flux_vector but not yet for the flux offsets.

**Comment by wvlothuizen** [comment]
too old
