### ISSUE TITLE
Sequencer improvements 

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#103]
Adding a list of improvements after discussion with @elrama- 
@gtaifu , take a look at these kind of issues as they might be relevant for the development of CC 
- [x] automatically add compensation pulses at end of sequence 
- [x] add a notion of pulse type and allow for type dependent buffers 
- [ ] #91 composite pulse (function that turns two pulses into single pulse object) 
- [x] #85 All pulse params into a (qasm like) single dictionary 
- [x] way to add many pulse parameters to a qubit without hardcoding (I have an idea for this)
- [ ] Smart reloading. Only reload if parameters changed

**Comment by elrama-** [comment]
- [] Redesign code (not sure which part) to make the sequence plot a one-liner
