### ISSUE TITLE
Live plotting linked axes

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#108]
When making the tektronix sequencer viewer, I figured out how to link axes. 
This would also be a useful feature for the MC live plot.

**Comment by AdriaanRol** [comment]
Another idea for a plotting enhancement. The liveplot contains a save function. I think it would be a good idea to have that saved at the end of a measurement. 

(added to this issue to save it together with the plotting).

**Comment by MiguelSMoreira** [comment]
Closed due to inactivity
