### ISSUE TITLE
Inconsistency in tomography labeling

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#112]
The tomography index reordering functions contain an inconsistency. 

It seems that the ordered pauli vectors switch the single qubit operations around. 
I make this conclusion based on converting density matrices generated by quantumsim not giving back the right single qubit operators. 

Note that this bug does not affect the tomographies themselves as whatever labeling convention is used corrects the inconsistency (inverted twice). 

The offending function is "tomo.pauli_ops_from_density_matrix".

**Comment by MiguelSMoreira** [comment]
Closed due to inactivity
