### ISSUE TITLE
Save whatever the plotmon is showing at the end of an experiment

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#114]
Since the liveplotting is kind of nice at the moment it would actually be nice to always save those figures anyways. Kind of easy to do so no reason not to (except maybe performance but I'll disable it when live plotting is disabled).

**Comment by AdriaanRol** [comment]
Just found out that this should trivial to implement. `Plotting_window.save('filename')`

**Comment by wvlothuizen** [comment]
too old, apparently solved
