### ISSUE TITLE
Migration of setups to beloved terminal

### ISSUE THREAD

**Issue by elrama-** [DiCarloLab-Delft/PycQED_py3#126]
We have agreed amongst several people that we should move back to running experiments from the terminal. The main issue right now is that the PyQTgraph versions installed on the computers don't allow for this.

After installation of the whole software in the 2 new measurement computers(In the Aprilia section) we checked that this is working now, and ready to migrate to the terminal.

The procedure is as follows:
- Update anaconda to 3.6
- install the new pyqtgraph: Currently the conda install command has an old version. Use the PIP INSTALL command, and it is tested to work. In case you are reading this a loooong time from today, the versions used in the test are attached at the end.

Setups remaining to migrate:
 - [ ] Maserati
 - [x] Maserati Probe

Package's version:
alabaster (0.7.9)
anaconda-client (1.6.0)
anaconda-navigator (1.4.3)
astroid (1.4.9)
astropy (1.3)
Babel (2.3.4)
backports.shutil-get-terminal-size (1.0.0)
beautifulsoup4 (4.5.3)
bitarray (0.8.1)
blaze (0.10.1)
bokeh (0.12.4)
boto (2.45.0)
Bottleneck (1.2.0)
cffi (1.9.1)
chardet (2.3.0)
chest (0.2.3)
click (6.7)
cloudpickle (0.2.2)
clyent (1.2.2)
colorama (0.3.7)
comtypes (1.1.2)
conda (4.3.13)
configobj (5.0.6)
contextlib2 (0.5.4)
coverage (4.2)
cryptography (1.7.1)
cycler (0.10.0)
Cython (0.25.2)
cytoolz (0.8.2)
dask (0.13.0)
datashape (0.5.4)
decorator (4.0.11)
dill (0.2.5)
docutils (0.13.1)
et-xmlfile (1.0.1)
fastcache (1.0.2)
Flask (0.12)
Flask-Cors (3.0.2)
gevent (1.2.1)
greenlet (0.4.11)
h5py (2.6.0)
HeapDict (1.0.0)
idna (2.2)
imagesize (0.7.1)
ipykernel (4.5.2)
ipython (5.1.0)
ipython-genutils (0.1.0)
ipywidgets (5.2.2)
isort (4.2.5)
itsdangerous (0.24)
jdcal (1.3)
jedi (0.9.0)
Jinja2 (2.9.4)
jsonschema (2.5.1)
jupyter (1.0.0)
jupyter-client (4.4.0)
jupyter-console (5.0.0)
jupyter-core (4.2.1)
lazy-object-proxy (1.2.2)
llvmlite (0.15.0)
lmfit (0.9.5)
locket (0.2.0)
lxml (3.7.2)
MarkupSafe (0.23)
matplotlib (2.0.0)
menuinst (1.4.4)
mistune (0.7.3)
mpmath (0.19)
multipledispatch (0.4.9)
nbconvert (4.2.0)
nbformat (4.2.0)
networkx (1.11)
nltk (3.2.2)
nose (1.3.7)
notebook (4.3.1)
numba (0.30.1)
numexpr (2.6.1)
numpy (1.11.3)
numpydoc (0.6.0)
odo (0.5.0)
openpyxl (2.4.1)
pandas (0.19.2)
partd (0.3.7)
path.py (0.0.0)
pathlib2 (2.2.0)
patsy (0.4.1)
pep8 (1.7.0)
pickleshare (0.7.4)
Pillow (4.0.0)
pip (9.0.1)
ply (3.9)
prompt-toolkit (1.0.9)
psutil (5.0.1)
py (1.4.32)
pyasn1 (0.1.9)
pycosat (0.6.1)
pycparser (2.17)
PycQED (0.1.0, d:\githubrepos\pycqed_py3)
pycrypto (2.6.1)
pycurl (7.43.0)
pyflakes (1.5.0)
Pygments (2.1.3)
pylint (1.6.4)
pyOpenSSL (16.2.0)
pyparsing (2.1.4)
pyqtgraph (0.10.0)
pytest (3.0.5)
python-dateutil (2.6.0)
pytz (2016.10)
pyvisa (1.8)
pywin32 (220)
PyYAML (3.12)
pyzmq (16.0.2)
qcodes (0.1.2)
QtAwesome (0.4.3)
qtconsole (4.2.1)
QtPy (1.2.1)
requests (2.12.4)
rope-py3k (0.9.4.post1)
scikit-image (0.12.3)
scikit-learn (0.18.1)
scipy (0.18.1)
seaborn (0.7.1)
setuptools (27.2.0)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.10.0)
snowballstemmer (1.2.1)
sockjs-tornado (1.0.3)
sphinx (1.5.1)
spyder (3.1.2)
SQLAlchemy (1.1.5)
statsmodels (0.6.1)
sympy (1.0)
tables (3.2.2)
toolz (0.8.2)
tornado (4.4.2)
traitlets (4.3.1)
unicodecsv (0.14.1)
wcwidth (0.1.7)
Werkzeug (0.11.15)
wheel (0.29.0)
widgetsnbextension (1.2.6)
win-unicode-console (0.5)
wrapt (1.10.8)
xlrd (1.0.0)
XlsxWriter (0.9.6)
xlwings (0.10.2)
xlwt (1.2.0)

**Comment by AdriaanRol** [comment]
@elrama- I just moved over maserati Probe

**Comment by antsr** [comment]
@elrama- Could you please explain, why you decided to move from notebooks to terminal? Is there anything that might be a problem for us if we continue to use notebooks in QuDev?

**Comment by AdriaanRol** [comment]
@antsr , There is no problem whatsoever if you continue to use notebooks. 
The reason for us to move away from notebooks is that we find that running prolonged experiments from the notebook caused two problems. Notebooks tend to slow down after prolonged use (lot's of cached output) and the code turns into spaghetti, making it difficult to translate it into nice routines/functions that we can easily integrate into PycQED. 

This is mostly a workflow decission and although I would recommend it you should be fine continuing as you please.

**Comment by AdriaanRol** [comment]
We are now using the terminal on whatever setup we want and also have functional notebooks. Closing this issue.
