### ISSUE TITLE
Standardized decoupling matrix calibration, analysis and flux control 

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#128]
This consists of puting the existing routines that are now in notebooks and done manual in easy to find places. It also involves updating the Flux control. 

- [ ] Experiment to measure the decoupling matrix 
- [ ] Analysis scripts for extracting the matrix 
- [x] Update the Flux control so that it obeys these conventions

**Comment by MiguelSMoreira** [comment]
Closed due to inactivity
