### ISSUE TITLE
Standardized dac arcs analysis 

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#129]
This consists of grouping the existing routines in easy to find example scripts. 

- [ ] Data extraction and filtering 
- [x] Plotting and fitting 
- [x] PSD analysis

**Comment by AdriaanRol** [comment]
With the exception of the data filtering this was done in #134 . Lowering priority to low as most of it has been done.

**Comment by AdriaanRol** [comment]
Update: working on this today. @Aypac has implemented a version of this in ma2. 

I will be making changes + adding tests to support the following 
- Allow the same analysis routine to be used for the pulsed and DC coherence arcs. 
- Add configurability to plots (issue raised by @NielsBultink ) 
- Look for any mismatches between version in PycQED and the one floating around in notebooks.

**Comment by MiguelSMoreira** [comment]
Closed due to inactivity
