### ISSUE TITLE
More meaningful linecuts in 2D live plotting 

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#132]
Currently the plotmon for 2D plotting shows linecuts all in the same color, making it hard to distinguish the different lines. 
It would be useful to make this a bit more fancy to enhance the contrast. 
I'll write some ideas down here. 
- Different color for each linecut 
- some interactive tool to select which one one wants to display 
- Only show last-N linecuts and fade them out (sort of like a persitence mode).

**Comment by MiguelSMoreira** [comment]
Closed due to inactivity
