### ISSUE TITLE
Standardized tools and workflow for data filtering 

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#136]
Currently doing analysis of the avoided crossings. 
A very common task is the filtering of data using masks. This is currently a quite manual process. I would argue that this should always remain a relatively manual process, however the workflow and tools could (and should) be standardized. 

Leaving this as an open issue for now to remember for later.

**Comment by MiguelSMoreira** [comment]
Closed due to inactivity
