### ISSUE TITLE
Discussion on Waveform Generation in Software & Hardware

### ISSUE THREAD

**Issue by gtaifu** [DiCarloLab-Delft/PycQED_py3#14]
In the meeting yesterday, I have the some ideas about the pulse generation.

##  Software & Hardware Implementation Separation
There should be a separation between the hardware implementation of the pulse generation and software waveform definition. 

For example, the following waveform generation framework would support this separation:
 
![shs](https://cloud.githubusercontent.com/assets/6672150/14531946/888bbba0-025f-11e6-97a5-e5dff8a94f2b.png)

Here I suggest a QuTech Uniform Waveform Format and a Generation Interface. The interface is written in Python in QCoDeS. The uniform format can be derived from the waveform format of AWG5014, CBox and QWG. **Universality** and **simplicity** are the two most important metrics for this uniform waveform format. 

Every kind of AWG receives waveform in its predefined format translated by dedicated waveform translator from the QuTech Uniform Waveform Format. For example, AWG5014 receives a list of samples which may last for several milliseconds in its own format file, and CBox receives the eight groups of samples indicating eight pulses and timing tape [(pulse number, interval), ...] presenting the combination of pulses. For most of the devices, dedicated waveform translators have already been developed in QCoDeS. 

In the upper layer, every user can easily write his own waveform generating function based on the Uniform Waveform Generation Interface. Specifying the time is based on 1) *the absolute time*, 2) *the interval between consecutive pulses* or 3) *the interval between the starting points of two consecutive pulses* can be determined by the user-defined wave generation functions. 

(If experiments only invoke waveforms in the QuTech Uniform Waveform Format, it could free the programmer to generate waveforms in more flexible methods. However, this assumption implies an idea: generating waveform and using waveform should be separated. I don't know if it is feasible in experiment.)

In this way, the software implementation is independent of the hardware implementation, and every user can have his own preferred way to generate the waveform based on the experiment requirements. If there come any new devices, only dedicated waveform translator requires to be developed, and all upper layer software structure requires little change.

However, developing such kind of waveform format might be timing-consuming. I cannot estimate the pros & cons of this method at this stage.

## Uniform Waveform Format Definition
Defining the format would be the most unclear part. It should possess the following properties:
Can be easily translated into AWG5014/CBox_AWG/QWG waveform format.
Flexible configuration parameters:
- interval
- pulse shape
- amplitude
- phase
- duration
- repetition times
- external trigger or not
- ...

I cannot go into too much detail because 1) I have little experience in carrying on experiments; 2) we are not sure if this method would help and further this proposal is going to be taken or not.

We can have more discussion on this.

**Comment by AdriaanRol** [comment]
Closing this issue as we have had enough discussion on this to have a clear view on what it looks like. 

We are going for a three step compilation sequence consisting of QASM->time-grid->ASM (this was discussed with @cdickel, @gtaifu and Bertels group )
