### ISSUE TITLE
Easy combination of detectors into composite detectors 

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#142]
A common use case is wanting to monitor e.g., the temperature while doing some other experiment. Currently this would require making a custom composite detector and testing if no subtle coding bugs creeped in. 

Just as the fact that we can now support measuring parameter objects directly I want to support combining multiple detectors into one. For this end I would overload the addition (`+`) operator to support the following. 

`detector_a + detector_b = detector_c`. 

I will not support a subtraction operator. 

While working on this it makes sense to also overload the `__repr__` of detector functions such that one can quickly get the following information: what quantities are being measured, what are the units.

**Comment by MiguelSMoreira** [comment]
Closed due to inactivity
