### ISSUE TITLE
Missing factor of pi in model for qubit dac arcs

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#143]
There is a missing factor of pi in the qubit_dac_to_freq and it's inverse (qubit_freq_to_dac). 

This missing factor of pi has no experimental consequences as it is taken into the "dac_flux_coefficient". However, the consequence is that when we are quoting units of Phi0 in the flux control we are off by a factor of pi. 

It is also possible that this bug propagates into analysis.

**Comment by MiguelSMoreira** [comment]
Closed due to inactivity
