### ISSUE TITLE
Confusion about integration_logging_det and integrated_average_detector

### ISSUE THREAD

**Issue by antsr** [DiCarloLab-Delft/PycQED_py3#146]
As far as I understand from the code the integration logging detectors are essentially the same as the integrated average detectors, only that they do not do any averaging and they take the number of segments as an initialization parameter instead of from the length of the sweep function, which they ignore. So could an integrated average detector be always used instead of integration logging detector, by setting the number of averages to 1 and passing as `sweep_points` a vector of length equal to the number of shots desired? In my opinion it would improve code readability even more, if in such case the sweep function was set to a `Hard_Repeat` sweep function which wouldn't have to do anything, and the AWG sequence was loaded by calling the sequence function directly.

**Comment by AdriaanRol** [comment]
@antsr , your observation is correct. The logging detector is an averaging detector without averaging. However, considering the diverse use cases (as in the type of experiments these are used for) and the different way they interact with the acquisition loop I think this is different enough to warrant a separate detector. 

Feel free te reopen the issue if you have any further question or disagree.
