### ISSUE TITLE
Resonator hanger models have inconsistent units 

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#150]
Wanted to quickly update the Homodyne analysis as the wrong units (Hz and GHz mixed) annoyed me. Ran into the units being inconsistent (there is even a comment saying that they are). 

Easy to fix but requires careful checking to not accidentally break things in other places. 

Problem also manifests itself in the default figures being generated. For the record the numbers that are being fitted do make sense and seem correct (correct freq extracted and quality factors that make sense). as far as I know this was OK a week ago before I merged some changes. 

Will look into this later. 

![image](https://cloud.githubusercontent.com/assets/6142932/24172067/27a98058-0e87-11e7-9857-1e0d07d1e5e6.png)

**Comment by wvlothuizen** [comment]
too old
