### ISSUE TITLE
Integrate purity RB in the conventional RB sequences and analysis

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#151]
We use RB to quantify how well our gates are performing and compare this to the (theoretical) T1 limit. It would be good to add purity RB ( Phys. Rev. Lett. 117, 260501 ) as an experiment to compare to. 

This is relatively easy to implement, given how we implemented RB but for now is not a top priority.

**Comment by MiguelSMoreira** [comment]
Closed due to inactivity
