### ISSUE TITLE
Bug in Tektronix_driven_transmon

### ISSUE THREAD

**Issue by lciorciaro** [DiCarloLab-Delft/PycQED_py3#167]
On lines 793-811 (in the measure_transients function), the variable 'MC' should be used, instead of getting the measurement control instance with 'self.MC.get_instr()' each time. Right now, the argument passed to the function has no effect at all.

**Comment by AdriaanRol** [comment]
As far as I know this has been solved. If anyone encounters this again, feel free to reopen.
