### ISSUE TITLE
Echo sequence does not yield good error message for 0 pulse delay

### ISSUE THREAD

**Issue by fluthi** [DiCarloLab-Delft/PycQED_py3#177]
If you feed the echo sequence a time vector that contains a 0 pulse delay element you will get an error message that is not meaningful.
The problem is that the pulses get added on top of each other, and hence the limit of the pulse height is superseded.
A good error message will fix allow for much easier debugging.

**Comment by MiguelSMoreira** [comment]
Closed due to inactivity
