### ISSUE TITLE
UHFQC sensible parameter names, docstrings and validators

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#184]
Currently most (not all) of the UHFQC is auto generated based on the ZI_python API. The advantage is that all functionality that exists is available from the PycQED driver. 

However, for some parameters it would be useful to add things like a docstring or slightly different arguments (such as modes not being integers but strings). This would require overwriting these parameters in the driver. This can be done in a way that uses the auto generated drivers as a starting point and adds some custom parameters that overwrite the existing ones. 

Good candidates for this would be giving names to some of the user registers or adding a docstring to them as well as adding more documentation on the user modes.

**Comment by AdriaanRol** [comment]
Starting a list of parameters to rename/clarify. 
- awgs_0_userregs_1 , 0 is results logging, 1 is input average
- awgs_0_userregs_0, specifies the number of shots in single shot mode, or nr_of_shots * nr_averages in int _avg mode. 

This list is not conclusive yet and will be updated.

**Comment by AdriaanRol** [comment]
A recent update to the ZI driver allows extracting these parameters from the Python API. We should update all ZI instrument drivers in a way that is consistent with how for example the DDM is done now.

**Comment by wvlothuizen** [comment]
too old
