### ISSUE TITLE
Motzoi calibration fails if parameter range is too big

### ISSUE THREAD

**Issue by fluthi** [DiCarloLab-Delft/PycQED_py3#186]
If you choose a too big parameter range for the Motzoi calibration, the result is more something sinusoidal, and not parabolic. This means that the fitting procedure yields very poor results and is unreliable.
Obviously this can be avoided by taking more appropriate parameter ranges, but still, for a hands-off automation over large ranges it is annoying.

**Comment by AdriaanRol** [comment]
@fluthi , I had indeed intended this only to be used close to the optimum. This should be good enough for automated hands off tuning as the motzoi parameter is not supposed to change significantly. 

Do agree that this is something that should be done. (I will reduce prio to low if you don't mind)
