### ISSUE TITLE
Rescaling tomography to ensure proper noise weighting in linear inversion  

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#189]
Today we did some testing with @lciorciaro , @elrama- and @leodicarlo and found some issues to happen when noise in the correlations are not weighted properly.

We tested that rescaling fixes this problem and have a working version now. We need to properly implement these changes and update the Tomo. 

@GitJaap you might also be interested in this.

**Comment by MiguelSMoreira** [comment]
Closed due to inactivity
