### ISSUE TITLE
Better way to deal with calibration points/normalization and rotation of axes

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#212]
There is a whole range of analysis scripts for all kinds of time domain experiments. All of these have the central underlying assumption that data is acquired in two quadratures (I and Q) and contains calibration points. These points are then used to rotate and normalize the data. As we are moving towards multiplexed experiments where we use a single weight function per qubit this assumption breaks, especially when it is hard to easily add calibration points (as is currently the case for some QASM sequences). 

As we use inheritance for all these functions I think they should work with different types of input. I think the following should be supported (note that a checkbox means it already is supported). 
- [x] 2 quadratures with calibration points
- [ ] 2 quadratures with calibration values based on SSRO experiment 
- [x] single qaudrature with calibration points 
- [ ] single quadruature with calibration values based on SSRO experiment 
- [ ] precalibrated axis in single quadrature. 

It is important that a solution is found that in turn makes all Timedomain experiments work regardless of the fashion in which the data is acquired.

**Comment by MiguelSMoreira** [comment]
Closed due to inactivity
