### ISSUE TITLE
Recent update to UFHQC detectors broke crosstalk suppression and axis normalization 

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#213]
After discussing with @NielsBultink we have found several problems. 

- The recent introduction of a scaling factor in the UHFQC detectors leads to much smaller values (typically mV) that when inverted and normalized (as the standard analysis procedure does) leads to a typical matrix elements >1000. While the maximum allowed value for elements is -2, +2. 
- The offset correction is disabled (commented out in the detectors). 

By temporarily disabling the scaling factor in the weights (setting it to 1 in int_logging and to 1/nr_averages in int_averaging), it is possible to get sensible values for the crossstalk suppression matrix. This is a workaround as it is still possible to get weird matrices when working with smaller signals or shorter integration times. A proper solution would use a normalized matrix for crosstalk, separate from the normalization and offset correction. 

Having separate modes for these detectors complicates matters a bit. The easiest solution would probably be to have a separate parameter in the qubit mode (and in the detectors).

**Comment by AdriaanRol** [comment]
@NielsBultink I enabled crosstalk suppression and setting of the suppression matrix in e8deb1d  but still find non-normalized axes using the following script. 

Will let it be for now. 
```python 
from pycqed.analysis import multiplexed_RO_analysis as mra
reload(mqm)

UHFQC2178.upload_transformation_matrix([[1,0],[0,1]])

mqm.measure_two_qubit_ssro(Starmon, 'QL', 'QR', no_scaling=True, crosstalk_suppression=False)

mu_matrix,  V_th, mu_matrix_inv, V_th_cor,  V_offset_cor = mra.two_qubit_ssro_fidelity(label='QL_QR')



UHFQC2178.quex_trans_offset_weightfunction_0(V_offset_cor[0])
UHFQC2178.quex_trans_offset_weightfunction_1(V_offset_cor[1])
# Does not work because axes are not normalized
UHFQC2178.upload_transformation_matrix(mu_matrix_inv)

mqm.measure_two_qubit_ssro(Starmon, 'QL', 'QR', no_scaling=True,
                           crosstalk_suppression=False)
```

![image](https://cloud.githubusercontent.com/assets/6142932/25314051/5373adca-283c-11e7-9d42-29093b04267c.png)

![image](https://cloud.githubusercontent.com/assets/6142932/25314053/560242d6-283c-11e7-9e6e-e6bff7517778.png)

**Comment by NielsBultink** [comment]
These seem perfectly normalised to me. 
Average of 0 shots= 0, average of 1 shots is 1. threshold is 0.5
Let’s discuss tomorrow. Niels

**Comment by wvlothuizen** [comment]
too old
