### ISSUE TITLE
Mirroring at boundaries for optimizations

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#215]
@elrama- I mention you here as you will most likely be experiencing this in the near future. 

When numerically optimizing adiabatic flux pulses we experience that the optimization sometimes hits values that are not allowed (resulting in diverging functions). When this happens, an error is raised and the optimization fails. 

I propose a solution in which values get mirrored around their boundary (if a boundary is specified in the parameter). This would have the effect that if the boundary is optimal, the optimizer will stick to the boundary. If the boundary is not optimal but a value beyond the boundary is accidentally set, it can converge to a value beyond the boundary. However, this can easily be converted back. 

For the current problem we will implement a clipping solution, however we note that this implementation in the core of how we handle optimizations would be advantageous.

**Comment by AdriaanRol** [comment]
Related to #607

**Comment by MiguelSMoreira** [comment]
Issue appears to have been fixed in related issue
