### ISSUE TITLE
Update spectroscopy AWG sequences to new format

### ISSUE THREAD

**Issue by elrama-** [DiCarloLab-Delft/PycQED_py3#22]
All awg sequences for TD experiments are described using pulse_pars and RO_pars that define channels, markers and pulse parameters in a flexible way. (see single qubit tek sequence elements). 

The spectroscopy sequences still rely on an old format that contains hardcoded channels. This should be updated 
- [x] make new (modular) awg sequence and add to single qubit tek seq elements 
- [x] replace CW-spec and Pulsed-spec sequences in heterodyne instrument. 
- [ ] Clean up (delete) old versions

**Comment by AdriaanRol** [comment]
@elrama- this has been implemented right?
