### ISSUE TITLE
Simplified calibration routines for qubit object. 

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#240]
(This relates to #42 which deals with the parameter naming. )

In addition to cleaning up the parameter names in the qubit object (#42), we should clean up the calibration functions. The dependency graph based tuning provides some constraints that provide structure to this process. Discussions with @fluthi and @cdickel provided some more ideas on this. 

I propose the following 
- every distinct calibration step corresponds to a single function in the qubit object
- every distinct calibration step corresponds to a single node in the dependency graph
- the calibrate funtions can be called blindly (i.e., without specifying any arguments) and will return either a value indicating it was succesful or a boolean False indicating failure. 
- calibration functions (e.g, find_frequency_spec, calibrate_freq_ramsey) are specified in the qubit_object abstract base class and within them call "measure_xx" functions that are specific for different hardware configurations. 
- the interface of every measure_xx function will be specified in the qubit_object abstract base class. 

What will change? 
- currently the functions often require specifying some arguments to make it work or encompass multiple different calibrations (e.g. find frequency does both the cw_spec, pulsed_spec and ramsey method). 
     - sensible defaults will be specified
     - functions will be split up when required. 

We will need to argue over what should and should not be included in a calibration to determine what functions will be required. I'd appreciate feedback from everyone as much as possible. 

Below is an initial graph I'm using now. I'd like some more input on what extras will be required (such as extracting dac arcs, decoupling matrices etc). 
![image](https://cloud.githubusercontent.com/assets/6142932/26678498/157cb1b6-46d1-11e7-8872-008efc96c9e9.png)

**Comment by MiguelSMoreira** [comment]
Closed due to inactivity
