### ISSUE TITLE
Calibration points for soft sweeps

### ISSUE THREAD

**Issue by lciorciaro** [DiCarloLab-Delft/PycQED_py3#250]
There are some types of experiments for which there currently is no straight-forward way to add calibration points, mostly in soft sweeps. The reason is, that there is no good way to add the sequence of calibration pulses at the end of the measurement.
A way to solve this would be the following:
In the `finish()` method of the detector, include the measurement of the (usually 4) calibration points, and add them to the data set. This way calibration points can be measured independent of the sweep that is used.
Also this should not break the analysis (too much), since the analysis will find the calibration points where it expects it, i.e. the last points of the data set.
The qumis file specifying the sequence for the measurement of the calibration points doesn't have to be generated every time, but could be stored somewhere, since it should never change.

**Comment by wvlothuizen** [comment]
too old
