### ISSUE TITLE
Make distinctin between raw data and processed data in maV2.0

### ISSUE THREAD

**Issue by tstavenga** [DiCarloLab-Delft/PycQED_py3#300]
- rename `data_dict`->`raw_data_dict` . add comment to the denote that this reflects exactly the state of the data on disk. 
- add a new attribute `processed_data_dict` 
- avoid use of  analysis class attributes to store data  (e.g., don't do `self.my_proc_data` but do `self.processed_data_dict['my_proc_data']`)  and add comment to this effect. 

These changes need to be retroactively applied to old analysis for V2.0 (up to now only flipping analysis and Nanowire analyses)

**Comment by AdriaanRol** [comment]
@tstavenga I was wondering if you made any progress on integrating the awesome TStavenga analysis into a PR. Would be great to see that.
