### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by peendebak** [DiCarloLab-Delft/PycQED_py3#305]
The `setup.py` specifies the package is python 3.5, but `ModuleNotFoundError` was only introduced in python 3.6. The `ModuleNotFoundError` is in `PycQED_py3/pycqed/measurement/waveform_control/pulsar.py`

Soluton: either replace the `ModuleNotFoundError` with an `ImportError`, or adapt the `setup.py`.

@AdriaanRol

**Comment by AdriaanRol** [comment]
@peendebak we should change the setup.py to 3.6 then. 

I'll find some time to fix it but it has a low prio for now

**Comment by wvlothuizen** [comment]
too old
