### ISSUE TITLE
pulse generation extremely slow

### ISSUE THREAD

**Issue by peendebak** [DiCarloLab-Delft/PycQED_py3#306]
Since updating to the latest version of pycqed the pulse generation is extremely slow. In particular the `Pulsar.ideal_waveforms` is very slow.

On our system there is a loop over all channels (12 for our system):
```
        for c in self.pulsar.channels:
            wfs[c] = np.zeros(self.samples(c)) + \
                     self.pulsar.channels[c]['offset']
            tvals[c] = np.arange(self.samples(c)) / self._clock(c)
```
Each call to `self.samples(c)` take 500 ms, each call to `self._clock(c)` about 100 ms. This part of the code therefore already takes 13 seconds, the code in the remainer of the function takes even more time.

The code mentioned above was added in commit 512b0ba6827ca50c950d4e706b37b1a261cb07c5. Was this tested with a tektronix 5014?

@AdriaanRol  @antsr

**Comment by antsr** [comment]
The code was tested on a Tektronix AWG5014. There were also timing issues for us at first, but they got solved when I made the Pulsar object query all the clock frequencies of the AWGs before creating the element waveforms in `Pulsar.program_awgs`. The average percall time for `Element.ideal_waveforms` was then 19 ms.

Are you trying to create the waveforms outside of the `Pulsar.program_awgs` function? If yes, then you could call `pulsar._clock_prequeried(True)` before the waveform generation. This makes the pulsar ask all AWGs for their clock frequencies and stores them. Later you could call `Pulsar._clock_prequeried(False)` if you ever plan to change the AWG clock frequency.

**Comment by peendebak** [comment]
@antsr Thanks, setting `_clock_prequeried` to `True` makes a huge difference. Is there somewhere we could document this, or somehow add a warning? 

PR #307  is still usefull for people with changing clock frequency, but I will not optimize the PR further.
