### ISSUE TITLE
CCLight driver enhancements 

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#310]
While moving the CCLight driver from the ElecProj_CCL repository I ran into several small issues. Normally these would be things for a code review (they are quite small) but as that moment has already passed I will make a small list here. 

- [x] Connect message does not display correct message, there is no "firmware" version in the IDN dictionary but there is a fwVersion key. Overriding the connect message will solve this
- [ ] the "unit" attribute of parameters is not used in the auto generated parameters, this is particularly important for the `vsm_channel_delayxx` parameters where it is not clear what units the integers are in (clocks? ns? at what clock frequency?) 
- [ ] Int's are used to represent Booleans, they should just be bools. 
- [ ] the json parameter file extracted is saved with the extension .txt, we should just use .json 
- [ ] Some docstrings are quite unclear. Specific examples are 
      - The distinction between `run` and `enable` 
      - What does the `timing_queue` actually show? Does this differ from `executuion_done`?
      - `num_append_points`? I have no clue what this is
- [ ] The file CCLightMicrocode seems to have quite some functions that already  exists in the utilities module or functions that could be done using the QCoDeS validators (check_int). 

I would also propose some changes. 
- [ ] rename `upload_microcode` to `upload_controlstore` to have a more explicit distinction with `upload_instructions`

@kel85uk

**Comment by gtaifu** [comment]
@AdriaanRol 
General message:
The docstring is stored in CC-Light.  Some modification is required on the C++ programming side. Lets look into this next week after the interface verification work is done.

Reply to each point:
- See general reply.
- `vsm_channel_delayxx` has the unit of `2.5 ns`.
- Boolean issue. See general reply.
- You can do that in Python.
- `run` and `enable` are the same as CBox. `enable` means activating the processor, instructions will be fetched. `run` means the time line is started. timing_queue will tell you the timing queue is empty or not. execution_done tells you that the processor has executed all instructions in the program, which is the result of the `stop` instruction and suggested to be appended to the end of the program by the assembler or the compiler. `num_append_points` is used to control VSM. we can discuss it later.
- Yes. Please simplify it.
- Please rename `upload_microcode` to `upload_controlstore`.

**Comment by wvlothuizen** [comment]
too old
