### ISSUE TITLE
Reading out parameter `num_append_points` unexpectedly sets the value 

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#311]
### Steps to reproduce
1. Read out the parameter multiple times 
2. Verified on scope that the value changes
3. Reading out again gives the changed value 

### Expected behaviour
Reading out should not change the value, only read it. 
![screenshot 2017-09-08 10 26 40](https://user-images.githubusercontent.com/6142932/30202923-7445738e-9480-11e7-84ec-779ad2acb18c.png)

**Comment by AdriaanRol** [comment]
@gtaifu as far as I know this was fixed corrrect?

**Comment by gtaifu** [comment]
Yes. It is a firmware bug and was fixed since CC-Light v0.5.0.
