### ISSUE TITLE
Uploading instructions without disabling QuMA can raise queue empty error

### ISSUE THREAD

**Issue by gtaifu** [DiCarloLab-Delft/PycQED_py3#317]
The standard method of uploading instructions and run it is (assume the CCLight object is `ccl`):
1. `ccl.run(0)`, `ccl.enable(0)`
2. `ccl.upload_instructions(qisa_fn)`
3. `ccl.enable(1)`, `ccl.run(1)`

These steps are simple but important. Since last week I encountered a **queue empty bug**, which is raised by disobeying the above steps: the processor is not disabled before uploading instructions.

So, it is suggested the Python driver can take care of disabling QuMA (step 1) before uploading instructions (step 2).

**Comment by jacobdesterke** [comment]
Should actually be solved on the CCLight software. Uploading instructions while QuMa is still running and enabled should raise an error or should automatically disable and stop QuMa.
