### ISSUE TITLE
convert Tektronix_driven_transmon  to Pulsar_driven_Transmon

### ISSUE THREAD

**Issue by brianzi** [DiCarloLab-Delft/PycQED_py3#318]
since pr #269 changed the pulsar to support multiple awgs, the tektronix_driven_transmon does not follow this paradigm and in fact is broken in several places. It should be converted to a pulsar-driven transmon, and the issues should be fixed.

### Steps to reproduce
1. Just try to use the Tektronix_driven_Transmon :)

### Labels 
In both cases, apply the correct labels to the issue. 
- choose one label from the type (type:) labels and one priority (prio:) label, optionally add a label from the cat: labels. 
For details see [contributing.md](.github/contributing.md)

### Solving an issue
If you want to solve an issue create a branch following the following naming convention: 
- category/#issue_number/descriptive_name

**Comment by MiguelSMoreira** [comment]
Closed due to inactivity
