### ISSUE TITLE
Timings of CBox_v3_controlled transmon for gated RO

### ISSUE THREAD

**Issue by brianzi** [DiCarloLab-Delft/PycQED_py3#329]
The timings of the CBox_v3_driven_transmon are not working as advertised, which makes it 
unusable for readout with a gated RF source (if one does not know about these problems and adjusts).

This occurs due to a combination of incorrect programming *and* a problem in the CBox. 

### Steps to reproduce

Set RO_acq_period_cw to 17895 ns, and set pulse_type to "gated_uhfqc". 
Start a spectroscopy. this loads the following qumis file on the CBox (trigger indices may vary):

```
mov r0, 20000   # r0 stores the cycle time , 100 us 
mov r1, 0       # sets the inter pulse wait to 0
mov r14, 0      # r14 stores number of repetitions
# Experiment: repeat the rounds for infinite times
wait 1
Exp_Start:
wait 3579
wait 20
trigger 0000010, 2
wait 2
trigger 0000011, 2
wait 2
trigger 0000010, 1596
wait 1796
beq r14, r14, Exp_Start       # Infinite loop
```

Hook up a scope to one of the triggers, measure a frequency of 37.037 kHz. This corresponds to 
a cycle time of 27000 ns.

There are two unexpected behaviours, one in the CBox program, the other in the CBox itself.

a) The "readout acquisition period" parameter was set to 17895 ns, so that the user expects that frequency. Instead, only the first `wait 3579` instruction corresponds to that time, and the readout
pulse section is added on top.

b) The sum of all wait instruction cycles corresponds to 26995 ns ( (3579 + 20 + 2 + 2 + 1796), times 5 ns per cycle). The CBox seems to add an additional cycle, for unknown reasons (maybe branching one instruction too early, executing the spurious "wait 1" before the loop?).

### System
CBox_v3

pycqed Proj/S7FC_merge_starmon branch.

**Comment by wvlothuizen** [comment]
Closing because CBox is old
