### ISSUE TITLE
Better UHFQC detector functions 

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#357]
The UHFQC detectors are not really easy to understand as was evidenced by the bug hotfixed in #355 . 

We should improve the UFHQC detectors such that such problems will not occur in the future.

**Comment by AdriaanRol** [comment]
Some additional functionality is required as proven by the nasty debugging today 
- Setting to set all readout interpretation settings to their defaults (to clear any memory effects) 
- Setting to copy all quex settings from one channel to another (used in correlation mode), currently some of them are still missing. 
- Settings to not have the device and qubit object RO lutmans interfere with each other (this is a bug that I ran into just now).

**Comment by wvlothuizen** [comment]
too old
