### ISSUE TITLE
Execute helper function to accept qumis instead of qasm

### ISSUE THREAD

**Issue by kel85uk** [DiCarloLab-Delft/PycQED_py3#364]
Change demonstrator_helper/execute_helpers.py to use qumis instead of qasm. This is to address Quantum_Infinity issue 73 for Project Release v1.0

**Comment by AdriaanRol** [comment]
@kel85uk I've created a QuantumInfinity label . Could you use this to tag any future QI related issues and PR's?

**Comment by kel85uk** [comment]
Sure, thanks!
