### ISSUE TITLE
minicircuits switch driver 

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#374]
@brianzi 
This exists on the S7FC branch. A PR to master or to QCoDeS master should be created.

**Comment by AdriaanRol** [comment]
@brianzi I noticed that there is an open PR for a minicircuits switch driver on QCoDeS (https://github.com/QCoDeS/Qcodes/pull/814/files) . If this is the same as the one you made and you think it is any good than we can just use that.

**Comment by brianzi** [comment]
Seems good, yes. I see it even uses channels, which I never understood... But I guess we can use that one. We don't have any of those switches anyway right now...

**Comment by wvlothuizen** [comment]
too old
