### ISSUE TITLE
cfg_qubit_idx causes readout to timeout if not equal to 0.

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#388]
When setting the CCL qubit object parameter cfg_qubit_nr to anything other than 0 a timeout error occurs. 

This variable is used in the CCL compilation and also for triggering the UFHQC. 

I suspect this has to do with the way the readout sequence works.

**Comment by brianzi** [comment]
This is true if the cfg_qubit_nr is set to 1, since qubit 1 is configured to be read out by the second UHFQC. Setting the qubit to 2 works fine.
