### ISSUE TITLE
Structure in parameter of qubit

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#42]
As discussed with @NielsBultink the parameters in the qubit object could have more structure. 

The example to emulate are the Zurich Instruments UHFQC parameters where a hierarchical structure is embedded in the parameter names. 

Solving this issue would consist of 
1. making a list of all the parameters, 
2. sitting together and grouping them together 
3. renaming the parameters to follow the new convention. 

This is now possible because we have a better overview of what the function of the qubit object is and it is more mature.

**Comment by AdriaanRol** [comment]
@elrama- @NielsBultink 
Hi Niels and Ramiro, I was thinking of merging all the qubit objects into a single file. There are two reasons for this. 
 - Eases finding relevant code when measuring as all inheritance is in the same place
- Should make it easier to in the future clean up this code. 
- Allows easier reloading when debugging. 

Related to this is also #99 that I discussed with Ramiro yesterday. 

Let me know if any of you has any issues with this, I couldn't see any but I wanted to make sure you are in the loop. (I won't do this immediately so you can respond).

**Comment by AdriaanRol** [comment]
Naming conventions for qubit object. 
While working on #320 I have to add all parameters. 
After a discussion with @brianzi we have come up with the following naming convention. We have gone over the list of parameters in the existing qubit objects and determined that all fit in this framework. 

```
    Naming conventions for parameters:
        (only for qubit objects after Sept 2017)
        Parameters are grouped based on their functionality. This grouping
        is achieved through the parameter name.

        Prefixes are listed here:
            instr_  : references to other instruments
            ro_     : parameters relating to RO both CW and TD readout.
            mw_      : parameters of single qubit MW control
            spec_   : parameters relating to spectroscopy (single qubit CW)
            fl_     : parameters relating to flux control, this includes both
                      flux pulsing as well as flux offset (DC).
            cfg_    : configuration, this can be info relevant for compilers
                      or configurations that determine how the qubit operates.
                      examples are cfg_qasm and cfg_f_qubit_calc_method.

            ""      : properties of the qubit do not have a prefix, examples
                      are T1, T2, etc., F_ssro, F_RB, etc., f_qubit, E_C, etc.

```


To prevent breaking this I will not be changing the existing qubit objects, however I would like to get some input on this naming convention. 

Let me know what you think @elrama- @antsr @NielsBultink @fluthi

**Comment by johu2** [comment]
Do you foresee using this structure to structure the HDF5 content a bit more?

**Comment by AdriaanRol** [comment]
@johu2 , I am currently implementing this on the CCL qubit object. This would mean that data saved based on those instruments will automatically follow this naming convention, and therefore have more structure. 

If you want it in the QuDev qubit object (which seems a bit outdated on our master branch) then you would have to update to follow the same convention.

**Comment by johu2** [comment]
@AdriaanRol I had in my mind something else. At the moment the data files have a top level group. One of them is called "Instrument settings" which has a group per instrument. Each instrument has all of it's settings as an attribute of the group. I was wondering, if underscores ("_") would perhaps also make instruments have subgroups to distribute the attributes. Just a thought.

**Comment by AdriaanRol** [comment]
@johu2 , this makes me think a lot of parameter trees. Where rather than the grouping being done using underscores it is done by actually having nodes with subnodes (like the ZI API). I would like to propose such a structure (with all the support that comes with it) to the QCoDeS core as I believe this kind of grouping can be greatly benificial to the usability of instruments. If such a feature is implemented it would also do what you describe (i.e., give more structure to the HDF5 files). 

To directly answer your question though, I have no plans to implement that. For now you'll have to do with alphabetical sorting of parameters.

**Comment by AdriaanRol** [comment]
Closing as this now exists in the CCL qubit object.
