### ISSUE TITLE
Trigger issue betwen Tektronix AWG5014 and UHFQC

### ISSUE THREAD

**Issue by brianzi** [DiCarloLab-Delft/PycQED_py3#422]
### Steps to reproduce
1. Q.measure_T1() -> all works fine, everytime
2.Q.measure_T1(upload=False) -> very noisy data. Looks like a trigger missed?

Happens with all time domain measurements. 

Labserver and UHFQC version 48740.

**Comment by AdriaanRol** [comment]
@brianzi what kind of qubit object? (I assume tektronix driven?)

**Comment by wvlothuizen** [comment]
too old
