### ISSUE TITLE
Export non-experimental data to HDF format

### ISSUE THREAD

**Issue by xabomon** [DiCarloLab-Delft/PycQED_py3#432]
Exporting any non-experimental data to HDF file with the same structure as experimental data to make use of the same analysis tools.

### Solving an issue
- Create a function to fold any data (e.g. quantumsim) into a HDF file.
- Make use of analysis tools as in experimental data.
- Create more reliable and comparable simulation vs experiments results.

### Comments
- Already used to compare Multi-round parity check measurements by Adriaan with Quantumsim simulations by Xavi.
- Generalize the used procedure.

**Comment by MiguelSMoreira** [comment]
Closed due to inactivity
