### ISSUE TITLE
timing calibration protocols

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#450]
Timing calibration protocols for CCL transmon and device object
- [ ] mw-ro timing
- [ ] mw-vsm timing
- [ ] mw-flux timing

**Comment by AdriaanRol** [comment]
The timing calibration protocol exists but is not well integrated and the analysis is very manual. Should be improved.

**Comment by AdriaanRol** [comment]
Current useful microwave ro timing is to do an AllXY experiment and slide the DIO delay.

**Comment by MiguelSMoreira** [comment]
Closed due to inactivity
