### ISSUE TITLE
Usecases support for CCL_Transmon class

### ISSUE THREAD

**Issue by elrama-** [DiCarloLab-Delft/PycQED_py3#457]
CCL_Transmon currently contains experimental procedures with calls particular to the use-case of AWG8+VSM.

The decision was to support with/without VSM cases as well as AWG8/QWG cases. In the end we want procedures that support the following cases:

![usecases_ccl_transmon](https://user-images.githubusercontent.com/11042934/38666193-a6020b54-3e3e-11e8-8a18-f4111a9e6f8a.png)

As we go editing the code to add the support, we will be adding the pertaining explanations and refining the flow strategy for the four cases.

**Comment by AdriaanRol** [comment]
The CCL has been used to support all these use cases. I agree that documentation can be improved but I'm closing this issue.
