### ISSUE TITLE
No fixed point notion in CCL sequencing

### ISSUE THREAD

**Issue by elrama-** [DiCarloLab-Delft/PycQED_py3#468]
> As it is now, there is no way in CC Light sequencing to report or set a repetition rate in a straightforward way.
> Currently the repetition rate needs to be "counted" from the QISA file or the QISA timings file.
> Even worse, all the code existing for CCL sequencing does not ensure that different segments of each sequence have the same duration.

Discussion:
> I know @AdriaanRol is strongly convinced that this should not affect things. I am strongly convinced it should.
Arguments should be listed below(will work on that)

Improvements that need to be done:
[  ] Call that allows sequencing for controlling total time of a segment. something on the lines of 
def fix_kernel_duration(program: openql_program, kernel_duration: float)
Output: program where kernels(segments) have all the same duration.
[  ] Call that allows to report repetition rate of a given sequence:
def report_repetition_rate(program: openql_program)
Output: float with a triggering rate or period interval.

**Comment by elrama-** [comment]
Experimental evidence that it matters:
![phase_vs_pop](https://user-images.githubusercontent.com/11042934/39778404-7f093446-5306-11e8-96b2-f4e51e0f43c1.PNG)
![li-tomography_exp_vqe_t114_p0](https://user-images.githubusercontent.com/11042934/39778731-6b14fb18-5307-11e8-9b9b-d7f52f73b2d5.png)

**Comment by AdriaanRol** [comment]
@elrama- , Do I understand correctly that this is resolved by @gtaifu's recent update to the CCL? If so, please close the issue, if not please explain why not.

**Comment by AdriaanRol** [comment]
@elrama- Closing this issue as we understand the underlying problem and as I understand you have a way of implementing this by hand in your programs.

**Comment by elrama-** [comment]
@AdriaanRol indeed. I think it is a good idea to write down the solution, It does not concern the code itself, but a good "practice" or procedure to use it.

This problem (lack of fixed point correction) arises at sequence design time. If smartly approached, we can overcome it easily. 

THIS PROCEDURE IS TO BE FOLLOWED AT OPENQL Program creation step (the procedures of multi_qubit_oql.py and single_qubit_oql.py for example).

1. When designing a sequence for a given experiment, define first a skeleton of the sequence, something like

gate1 q0
gate4 q0,q1
gate2 q0 | gate3 q1
measz q0
measz q1

This skeleton needs to be able to allocate all the cases of the sequence (another way to say this is: all the SEQ segments or OQL kernels). For example, if we wanted to do tomography, gate2 and gate3 would be changing with the tomographic pre-rotations. If we wanted the last points to be calibration points, we would put to identity everything but gate2 and gate3.

2. For actually building the sequence, implement a for loop for each segment/kernel. Inside this loop, implement the control flow to assign the desired gates to each slot.

3. If one desires to add Fixed-Point correction, add wait times after or before the experiment, in order to match the repetition rate desired. If using CCLight, the .tqisa file (after compilation) prints the concrete timings, allowing for wait-times to be readjusted.

Recall that frequencies of the frames involved (qubit drives) must be multiples of 1/rep-rate. For example, if setting a repetition rate of 200us (100000 cycles in tqisa), drive frequencies need to be rounded to 1/200us = 5 kHz.

Summary of procedure:
1. Define skeleton strategy for sequence
2. Implement flow control for gates
3. If desired Fixed-Point correction, allocate wait-times along those gates. Use the tqisa to make your life easier.

Cheers, R.
