### ISSUE TITLE
Replace usage of old SSRO analysis with v2 one

### ISSUE THREAD

**Issue by Aypac** [DiCarloLab-Delft/PycQED_py3#470]
Right now, the old SSRO analysis is often used (often with many if's):
![screenshot from 2018-05-09 17-55-40](https://user-images.githubusercontent.com/10585956/39825910-4961e308-53b3-11e8-8819-e8a046e779ec.png)

- Unify the use of these, extract the desired data correctly.
- Make the new Multiplexed SSRO use the new single SSRO to obtain better results
- (Remove old analysis)

**Comment by AdriaanRol** [comment]
The analysis v2 now completely replaces the v1 analysis for the single qubit case. It is still being used in the mux RO analysis that @elrama- is currently working on. 

Once the new v2 analysis is complete and stand alonge, we should be able to delete the old SSRO analysis.

**Comment by MiguelSMoreira** [comment]
Closed due to inactivity
