### ISSUE TITLE
Update to OpenQL v0.5.0

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#479]
OpenQL was recently updated. 
Currently we use a specific commit based on the 0.3.x version. There are some backwards incompatible changes that we will need to address. It is important we stay up to date with the latest release of OpenQL in order to be able to give proper feedback to @imranashraf .

**Comment by slavoutich** [comment]
Blocks me from pushing tests update for generating Quantum Infinity configuration files (#496).

**Comment by AdriaanRol** [comment]
Text below is copied from OpenQL issue # 146

## Backwards breaking changes 
- Target qubit of any gate is now always a list. 
`p.gate('gatename', q0) -> p.gate('gatename', [q0]) -> `

- Order of arguments of `Program` and `Kernel` changed 
`p = ql.Program("aprogram", nqubits, platform) -> `p = ql.Program("aprogram", platform, nqubits)` 
- set option changed 
`ql.set_ouput_dir(my_dir) -> ql.set_option('output_dir', my_dir)`

- Config file 
`two_qubits_gate -> two_qubit_gate`
## New features 
### Assigning measurements to a register 
```
rs0 = ql.CReg()
rs1 = ql.CReg()

k.gate('measure', [0], rs0) # not yet incompatible with multiple measurements 
k.gate('measure', [1], rs1) # not yet incompatible with multiple measurements 
```

### Classical operations 
Asinging outcome to a register 
```
rd = ql.CReg()
k.classical(rd, ql.Operation(rs0, '==', rs1)
```

### For loop 
```
k1 = ql.Kernel('some kernel', platform, nqubits)
k1.gate('x', [0])
p.add_for(k1, 10)
```

**Comment by AdriaanRol** [comment]
Upgraded priority to high as we found bugs that affect the QuantumInfinity.

**Comment by AdriaanRol** [comment]
This is currently working and deployed on master.

**Comment by wusis** [comment]
Newbie, sorry for bothering but: where can I find the OpenQL v0.5.0? I failed to install since the OpenQL I downloaded from pypi.org/project/openql/ is of 0.0.1.dev1.

**Comment by AdriaanRol** [comment]
@wusis , The OpenQL package we are using is developed by the Quantum Computer Engineering group in Delft and is not yet publicly available. OpenQL is a compiler framework that we use to generate instructions specifically for our central controller. It is a distinct project from the one available on PyPi. 

Everything in PycQED (with the exception of the tests) will work fine without OpenQL.
