### ISSUE TITLE
Analysis v2 (and probably a lot of other classes) keep cluttering the RAM

### ISSUE THREAD

**Issue by Aypac** [DiCarloLab-Delft/PycQED_py3#489]
When using any analysis v2, the object will be stuck in your memory until you restart the Kernel, because it contains self-references and thus does not get deleted by the garbage collector (gc). The MWE is this:

```
class A:
    def __init__(self):
        self.test = np.random.rand(150000000) #Take up some RAM
        self.s = self.b #Create a self-reference (n.b.: self.s = self would work the same)

    def b(self):
        return 0

a = A() #Create an instance and store a reference in a
del a #Delete the reference to the created object
#The gc should automatically free the memory this object was occupying now
```
This will block take several hundred MB of your RAM until you restart your Kernel, where it won't if you remove the line `self.s = self.b`. This is because the gc only deletes objects, that have no reference to it, but this object does (within itself).

This basically happens in almost every v2 analysis when we specify the plotfn in the plot_dict.

Possible solutions (other than avoiding self-references altogether) are given here: https://stackoverflow.com/questions/27628291/python-deletion-of-self-referencing-object

This should also be taken into account when writing future modules!

**Comment by Aypac** [comment]
One can find references to an object with

```
import gc
import sys
refs = gc.get_referrers(theobject)
print('Found references: ',len(refs),' [len(gc.get_referrers)] ',sys.getrefcount(ana),' [sys.getrefcount]')

for r in refs:
    print(type(r))
```

**Comment by AdriaanRol** [comment]
I found the following article on garbage collection in python. It looks like gc.collect() (which get's periodically called) should already solve this if this is indeed due to the circular reference. 
https://rushter.com/blog/python-garbage-collector/

I need to think a bit more about this in any case.

**Comment by wvlothuizen** [comment]
too old
