### ISSUE TITLE
CCL transmon object sets fluxcurrent channel through index, not name

### ISSUE THREAD

**Issue by kianvde** [DiCarloLab-Delft/PycQED_py3#490]
Branch: Develop

Fluxcurrent channel is set through index, e.g. in 1441:
`fluxcontrol.parameters[(self.cfg_dc_flux_ch())]`

This takes the value in self.cfg_dc_flux_ch as index in the `channel_map` dict of `QuTech_SPI_S4g_FluxCurrent`. This should be changed to either Qubit object name or being able to pass the name to force the channel through the qubit function you're running .

**Comment by AdriaanRol** [comment]
This has been resolved.
