### ISSUE TITLE
Random (Illegal Instruction) core dumps for test_cz_simulations.py

### ISSUE THREAD

**Issue by kel85uk** [DiCarloLab-Delft/PycQED_py3#494]
test_cz_simulations.py program is unreliable, as it seems for this particular script, sometimes it passes, and sometimes it fails.

Consider the same running code with nothing but a modification in comment for the different test outcomes:

![image](https://user-images.githubusercontent.com/6287181/43891158-f4b0296a-9bc8-11e8-8107-47f1b44197f6.png)

![image](https://user-images.githubusercontent.com/6287181/43891116-db8f4056-9bc8-11e8-8da4-fa143f1217ec.png)

**Comment by kel85uk** [comment]
After a brief check, seems like Travis could be spawning docker containers within processors which might not have certain instruction sets (avx2?). One of the libraries being used is prone to such problems.

See this: https://github.com/p4lang/p4c/pull/973

**Comment by AdriaanRol** [comment]
@kel85uk , I have disabled the tests in PR #495 .

**Comment by slavoutich** [comment]
The same in #496

**Comment by wvlothuizen** [comment]
too old, not using Travis anymore
