### ISSUE TITLE
Migrage from `logging.warning` to `warnings.warn`, where possible.

### ISSUE THREAD

**Issue by slavoutich** [DiCarloLab-Delft/PycQED_py3#501]
`warnings.warn` issues a non-interrupting exception object, that can be tracked (`warnings.catch_warnings` will turn it into exception), muted, etc. `logging.warning` prints a string to log, that makes it hard to debug. 
Also, `logging.warning` produces some garbage in tests output, while `warnings.warn` are accurately formatted, and also can be tested for emitting, where needed, for example:

```
with pytest.warns(UserWarning, 'Your argument is strange'):
    f('some strange argument')
```

My proposition is:

1. Replace all `logging.warning` to `warnings.warn`.
2. Pin all points, when we actually need to forward warnings to the log file, and use there [`logging.captureWarnings`](https://docs.python.org/3/library/logging.html#integration-with-the-warnings-module).

**Comment by wvlothuizen** [comment]
too old
