### ISSUE TITLE
QWG IORear DIO interface

### ISSUE THREAD

**Issue by nyxus** [DiCarloLab-Delft/PycQED_py3#504]
This issue is a placeholder for all changes to the QWG device driver that are related to the new IORear_DIO board. See:
 
- https://github.com/DiCarloLab-Delft/QuTech_AWGmodule/issues/135 - Main IORear_DIO implemention issue
- https://github.com/DiCarloLab-Delft/QuTech_AWGmodule/issues/173 - New waveform-codeword linking

**Comment by wvlothuizen** [comment]
too old
