### ISSUE TITLE
Analysis for pulsed Ramsey experiments 

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#508]
Should link up with other noise characterization analysis. 
Use the individual analysis by @FKMalina for the separate files.

**Comment by AdriaanRol** [comment]
Update on progress: 
There were two versions of this analysis, one made by @Aypac and one existing in notebooks that has been passed around from @quantumCryoCoder to @elrama- to @FKMalina . The second version only does not include data extraction but is a lot cleaner. 

The current status is: 
- Both variants give the same values for the derived quantities
- A lot of bugs have been squashed 
- The following (nice figures ) are now created 
- It is now a v2 analysis. 


![image](https://user-images.githubusercontent.com/6142932/46485145-69c46f00-c7fb-11e8-8a18-df7bbf782fd4.png)
![image](https://user-images.githubusercontent.com/6142932/46485152-6df08c80-c7fb-11e8-8007-7fa711dd3d61.png)
![image](https://user-images.githubusercontent.com/6142932/46485156-72b54080-c7fb-11e8-843a-1d8ac80380a0.png)
![image](https://user-images.githubusercontent.com/6142932/46485206-85c81080-c7fb-11e8-9341-22293a531abe.png)

The big problem is that I (and I'm not alone here) do not understand exactly what values are there. The code still contains a lot of magic numbers with references to papers that do not exist. (e.g., Martinis PRA 2003 (there does exist a PRB 2003)). 

I'll have to look into the physics to understand the details here, also because I want to use a modified version to understand the flux noise for the pulsed experiments.

**Comment by MiguelSMoreira** [comment]
Closed due to inactivity
