### ISSUE TITLE
hdf5 data files excesively large (~9MB per datafile)

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#509]
The filesize of each experiment has grown to about 9 MB per experiment. 
This is a bit too large. I believe this is caused by the snapshots that store the entire ZI parameter tree in an inefficient structure. It would be worthwhile to look into solutions to this.

**Comment by slavoutich** [comment]
If I understand the problem correctly, it might be good to try to investigate whether [xarray](http://xarray.pydata.org/en/stable/) fits for storing data. This would also bring some benefits for advanced possibilities in working with data.

**Comment by AdriaanRol** [comment]
@slavoutich I think this may not perfectly fit the desired application. 
We currently use hdf5 in two ways. 
- storing the main data, this is a flat table any n-dimensionness (if you will) is done by creating different columns. 
- storing a snapshot of all the settings. This is a nested dictionary, JSON seems the obvious candidate for this. 

I think that the xarray solution is aimed more at usability in python than the data storing backend (if I read the documentation). I only glanced this but I would be very interested in being proven wrong.

**Comment by AdriaanRol** [comment]
I will make two changes 
- Strip down most of the snapshot before saving. 
- Add a blacklist of banned non snapshotted parameters to some instruments drivers.

**Comment by AdriaanRol** [comment]
These changes are now included on the develop branch.
