### ISSUE TITLE
Clarity on chip topology used and consequences for how things should be connected

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#531]
This should be documented with figures and/or links to the relevant documentation in the CCL and QCC. It is also important to clarify what should be used different when using either QCC or CCL.

**Comment by elrama-** [comment]
Agreed to close. Will tackle this in another fashion. 
See
https://github.com/DiCarloLab-Delft/PycQED_py3/issues/534
https://github.com/DiCarloLab-Delft/PycQED_py3/issues/532
