### ISSUE TITLE
Proper use of channel and codewords for flux control.

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#532]
Currently the flux pulses interpret waveforms in an extremely hacky manner. This should be addressed and always use the proper codeword used for the proper edge.

**Comment by AdriaanRol** [comment]
@elrama- , you are currently fixing the last problems with this so I am assigning you. Once you've run a Chevron/cryoscope with the updated loading and ZI drivers I think we can close this issue.

**Comment by MiguelSMoreira** [comment]
Closed due to inactivity
