### ISSUE TITLE
DIO timing map for CCL device object

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#533]
Make the mapping for the timing configuration select one of two defaults so that the timing settings are properly set when using the device object. 

Currently the map to CCL DIO channels is hardcoded for the CCL.

**Comment by AdriaanRol** [comment]
While implementing this I found that the device object, which controls the DIO/coarse timing also controls the fine timing (used by setting channel per channel latencies). The problem here is that it uses a single parameter to set this for all qubits. This is incorrect and should be addressed.

**Comment by MiguelSMoreira** [comment]
Closed due to inactivity
