### ISSUE TITLE
Improve nyquist calculation for FluxArc analysis

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#541]
Using nyquist calc does not work for negative part of the flux arc. 
Disabling the nyquist calculation does not work for the outsides of the parabola as these points are generally of a higher nyquist order.

**Comment by AdriaanRol** [comment]
![image](https://user-images.githubusercontent.com/6142932/56587000-08ba8800-65e1-11e9-9739-642ee3a60371.png)

![image](https://user-images.githubusercontent.com/6142932/56587014-107a2c80-65e1-11e9-9565-28fb0beca942.png)

**Comment by MiguelSMoreira** [comment]
Closed due to inactivity
