### ISSUE TITLE
Readout pulse amplitude not uploading properly

### ISSUE THREAD

**Issue by lmjanssen** [DiCarloLab-Delft/PycQED_py3#549]
### Steps to reproduce
1. Get a UHFQC
2. Use a CCL Transmon qubit object
3.Preparre for continuous wave

### Expected behaviour
The output amp should be equal to ro_pulse_amp_CW

### Actual behaviour
The amplitude scaling is equal to this value

### System
PycQED QCC testing

Should be fixed in the RO lutman

**Comment by AdriaanRol** [comment]
We understand what was wrong here.
