### ISSUE TITLE
Spectroscopy timeout when mw_pulse_duration=40 in config

### ISSUE THREAD

**Issue by Timo1104** [DiCarloLab-Delft/PycQED_py3#554]
### Steps to reproduce
1. set mw_pulse_duration=40 in gc.generate_config;
2. try to perform CW spectroscopy (not tested with pulsed)

### Expected behaviour
Normal spectroscopy, updating live plot monitor every few data points.

### Actual behaviour
Gets stuck after few (if any) datapoints. Gives timeout error when 'q' terminating the experiment.

### System
PycQED develop branch

### Workaround
Set mw_pulse_duration to 20 in gc.generate_config should let everything run normally again
@AdriaanRol
Qisa files attached as .txt
[Pulsed_spec_20_ns.txt](https://github.com/DiCarloLab-Delft/PycQED_py3/files/3310892/Pulsed_spec_20_ns.txt)
[Pulsed_spec_40_ns.txt](https://github.com/DiCarloLab-Delft/PycQED_py3/files/3310893/Pulsed_spec_40_ns.txt)

**Comment by wvlothuizen** [comment]
too old
