### ISSUE TITLE
OpenQL tests failing; usage of qubits that are not in the platform

### ISSUE THREAD

**Issue by elrama-** [DiCarloLab-Delft/PycQED_py3#558]
The following tests are breaking, mostly because of one simple issue: wait operations written for inexistent qubits.

openql\test_clifford_rb_oql.py::Test_cliff_rb_oql::test_two_qubit_rb_seq
openql\test_multi_qubit_oql.py::Test_multi_qubit_oql::test_Chevron
openql\test_multi_qubit_oql.py::Test_multi_qubit_oql::test_conditional_oscillation_seq
openql\test_multi_qubit_oql.py::Test_multi_qubit_oql::test_two_qubit_tomo_bell
openql\test_pygsti_oql.py::Test_pygsti_oql::test_poor_mans_2q_gst
openql\test_pygsti_oql.py::Test_pygsti_oql::test_single_qubit_gst
openql\test_pygsti_oql.py::Test_pygsti_oql::test_two_qubit_gst

This refers to the global task of #557

**Comment by AdriaanRol** [comment]
Closed by #563
