### ISSUE TITLE
AvoidedCrossingAnalysis not detecting peaks properly

### ISSUE THREAD

**Issue by lmjanssen** [DiCarloLab-Delft/PycQED_py3#560]
### Steps to reproduce
1. Measure an avoided crossing, with a relatively small amount of flux points
2. Run ma.AvoidedCrossingAnalysis with the relevant timestamp
3. Open the relevant folder, and check the figure called 'filtered avoided crossing'

For many of the vertical linecuts, you will should be able to see a clear peak by eye 
### Expected behaviour
The fitting points are on these peaks, with the higher frequency branch in red and the lower 
in yellow
### Actual behaviour
The fitting method finds peaks that seem not to be there at all.

### System
**operating system**
Windows not-10 (8 I guess)
**PycQED branch**
ZI debug currently, but the issue is on every bracn
**PycQED commit**
see above

### Note
A dirty fix to this issue is to just measure a lot more finely on the flux axis, and then use filter_idx_high and filter_idx_low to take out the wrongly fitted points

### Solving an issue
If you want to solve an issue create a branch following the following naming convention: 
- category/#issue_number/descriptive_name

**Comment by AdriaanRol** [comment]
@lmjanssen , pasting a figure (generated by the analysis) would be very helpful.

**Comment by MiguelSMoreira** [comment]
Closed due to inactivity
