### ISSUE TITLE
Instruments:  Need to exclude parameters on snapshot  

### ISSUE THREAD

**Issue by nyxus** [DiCarloLab-Delft/PycQED_py3#566]
See https://github.com/DiCarloLab-Delft/QuTech_AWGmodule/issues/197

**Comment by nyxus** [comment]
In able to exclude parameters from the snapshot a change as to be made in Qcodes: https://github.com/QCoDeS/Qcodes/pull/1651. For now, I created a workaround by moving the code from qcodes to the `snapshot_bas()` of the QWG. When the PR is merged the code can be replaced with:
```python

snap = super().snapshot_base(update=update,
                             params_to_skip_update=params_to_skip_update,
                             params_to_exclude=params_to_exclude)
return snap
```
Note that this also needs to be applied to the HDAWG8 and the UHFQC.

**Comment by nyxus** [comment]
As described in https://github.com/QCoDeS/Qcodes/pull/1653 (different PR), we choose another implementation to exclude parameters from the snapshot. For now, a workaround is introduced until QCodes has the proper solution released. 

Todo: 
* Enable calling the super of snapshot base: `snap = super().snapshot_base(update=update, params_to_skip_update=params_to_skip_update)`
* Remove workaround
  * Remove code from `qwg.snapshot_base(...)`
  * Remove all `self._params_exclude_snapshot` occurences

**Comment by AdriaanRol** [comment]
Closed by recent PR

**Comment by nyxus** [comment]
I prefer to keep this issue open until qcodes has released the feature and we can remove the workaround.

**Comment by nyxus** [comment]
Reopened issue: workaround for the QWG is implemented, but the actual fix requires a new feature in QCodes. This feature is already provided (see PR above) but still needs to be released.

**Comment by wvlothuizen** [comment]
QCoDeS PRs 1651 and 1653 mentioned have been merged by now, so closing
