### ISSUE TITLE
Save fit results in a more meaningful way in data files. 

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#567]
The problem: 
- fits are saved based on the parameter they are fitted to. 
- This is a problem as there can be multiple functions fitted to the same parameter and as such complex analyses could overwrite the datasaving
- This is a problem because the name of the parameter is often changing in say a T1 fit, it can be raw_w0, lin_trans_w1 or something similar depending on which UHFQC mode is being used. This makes data extraction difficult for composite analyses.

**Comment by MiguelSMoreira** [comment]
Closed due to inactivity
