### ISSUE TITLE
Prepz openql command gets translated to some pulse

### ISSUE THREAD

**Issue by elrama-** [DiCarloLab-Delft/PycQED_py3#568]
While debugging some readout issues, I found out this problem looking at the scope.

The trouble is: The qisa file is fine, but the prepz instruction of openql generates a pulse (see pulse after the readout below)

![IMG_5885](https://user-images.githubusercontent.com/11042934/62226069-e68f8d80-b3b9-11e9-980b-ef3b524203f4.JPG)

The readout instruction lasts 150 cycles (3 us), the scope grid is set at 0,5 us, and we clearly see the pulse after that (when the next prepz is being played)

Attach qisa file below:
![qisa_sample](https://user-images.githubusercontent.com/11042934/62226313-500f9c00-b3ba-11e9-96f6-930e69f64f23.PNG)

**Comment by wvlothuizen** [comment]
too old
