### ISSUE TITLE
Iterative tune_to_freq procedure

### ISSUE THREAD

**Issue by elrama-** [DiCarloLab-Delft/PycQED_py3#569]
Over the last setup we have come across the need of a code that iteratively tune the qubit frequencies. Such a code already existed in the Python2 code (see snippet pasted below).

Such a code assumes no cross-talk (or at least does not actively take in consideration). The cross-talk problem is solved by the iterations, which should in principle involve smaller and smaller steps every time.

    def tune_to_frequency_spec(self, target_frequency,
                               threshold_frequency=1e-3, max_iterations=4,
                               freq_calc=None, **kw):
        suppress_print_statements = kw.get('suppress_print_statements', False)
        if isinstance(target_frequency, types.InstanceType):
            target_frequency = target_frequency.get_current_frequency()
        if freq_calc is None:
            freq_calc = self.freq_calc
        if freq_calc is 'flux':
            flux_val = self.calculate_flux_frequency(target_frequency)
            print 'Setting flux to', flux_val
            self.Flux_Control.set_flux(self.dac_channel, flux_val)
        elif freq_calc is 'dac':
            dac_val = self.calculate_dac_frequency(target_frequency)
            self.IVVI.set_dac(self.dac_channel, dac_val)

        for k in range(max_iterations):
            result = self.find_resonator_qubit_frequency(**kw)

            f_difference = target_frequency - result['f_qubit']
            if not suppress_print_statements:
                print 'Current frequency difference: %.9f GHz' % f_difference
            if abs(f_difference) < threshold_frequency:
                break
            if freq_calc is 'flux':
                flux_slope = self.calculate_flux_slope(flux_val)
                flux_val += f_difference / flux_slope
                self.Flux_Control.set_flux(self.dac_channel, flux_val)
            elif freq_calc is 'dac':
                dac_slope = self.calculate_dac_slope(dac_val)
                dac_val += f_difference / dac_slope
                self.IVVI.set_dac(self.dac_channel, dac_val)
        if abs(f_difference) < threshold_frequency:
            print 'Frequency tuned to within threshold frequency'
        else:
            print 'Failed to tune within threshold frequency'
        return result

    def tune_to_frequency_Ramsey(self,
                                 target_frequency,
                                 frequency_threshold=3e-5,
                                 max_iterations=5,
                                 stepsizes=[10, 30, 100, 200, 500],
                                 update_qubit=True,
                                 suppress_print_statements=False,
                                 **kw):
        '''
        Routine that tunes qubit to a certain frequency with it's flux
        channel.
        '''

        def tune_flux(qubit, detuning):
            flux_channel = qubit.get_dac_channel()
            flux = self.Flux_Control.get_flux(flux_channel)
            flux_slope = qubit.calculate_flux_slope(flux)

            flux_difference = float(detuning) / flux_slope
            self.Flux_Control.set_flux(flux_channel, flux - flux_difference)
            if not suppress_print_statements:
                print 'target frequency:', target_frequency
                print 'frequency estimate:', frequency
                print 'detuning: {} Hz'.format(detuning*1e9)
                print 'flux_difference:', flux_difference

        if self.TD_Meas.get_multiplex():
            raise NameError('Timedomain is set to multiplexed mode')
        # frequency = target_frequency
        # for k, stepsize in enumerate(stepsizes):

        if isinstance(target_frequency, types.InstanceType):
            target_frequency = target_frequency.get_current_frequency()
        stepsize_idx = 0
        stepsize = stepsizes[stepsize_idx]
        max_stepsize = stepsizes[-1]

        for k in range(max_iterations):
            TD_a = self.measure_Ramsey(drive_frequency=target_frequency,
                                       stepsize=stepsize, **kw)
            detuning = TD_a.detuning
            frequency = target_frequency + detuning
            T2_star = TD_a.T2_star
            next_stepsize = stepsizes[min(k+1, len(stepsizes)-1)]

            if (abs(detuning) < frequency_threshold) & (stepsize==max_stepsize):
                if not suppress_print_statements:
                    print 'Detuning {} Hz is smaller than threshold {}'.format(
                        detuning * 1e9, frequency_threshold)
                break

            if next_stepsize*60 > T2_star*3:  # all in ns
                if not suppress_print_statements:
                    print 'Step size {} ns is at maximum'.format(stepsize)
                max_stepsize = stepsize
            elif max_stepsize == stepsize:
                max_stepsize = next_stepsize

            if stepsize < max_stepsize:
                stepsize_idx += 1
                stepsize = stepsizes[stepsize_idx]
            # print 'flux_diffence', flux_difference
            # breaker
            tune_flux(self, detuning)

        if not suppress_print_statements:
            print 'Frequency tuning done.'
            print 'target frequency:', target_frequency
            print 'frequency estimate:', frequency
            print 'detuning: {} Hz'.format(detuning * 1e9)

        if update_qubit:
            self.set_current_frequency(frequency)

        result = {'frequency': frequency,
                  'frequency_stderr': TD_a.detuning_stderr,
                  'T2_star': T2_star,
                  'T2_star_stderr': TD_a.T2_star_stderr,
                  'stepsize': stepsize}
        return result

**Comment by MiguelSMoreira** [comment]
Closed due to inactivity
