### ISSUE TITLE
Clipping mode in MC does not work (by Jorge) 

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#607]
### Steps to reproduce
1. set clipping mode in MC to True using `MC.cfg_clipping_mode(True)`
2. Start an optimization that will hit the bounds of a parameter. Specific example is ro_pulse amp in a custom script by jorge (@jorgemfm27 , add it to comment below)
3. Wait until exception is raised. 

### Expected behaviour
Optimization should work and not raise an exception 

### Actual behaviour
A `ValueError` is raised (please add a screenshot @jorgemfm27 ) 

### System
**PycQED branch**
develop @jorgemfm27 check this is the right branch. 

**PycQED commit**
@jorgemfm27 add commit hash

**Comment by elrama-** [comment]
Seems to have been the wrong MC (uponwhich the setting was being tested).
Reopen in case of re-appearance
