### ISSUE TITLE
Fix default value ro_freq is null causing resonator scan to fail

### ISSUE THREAD

**Issue by Odrenal** [DiCarloLab-Delft/PycQED_py3#608]
### Steps to reproduce
1) use an new qubit object
2) run find_resonator_frequency()
3) watch it crash

### Expected behaviour
function does resonator scan

### Actual behaviour
function crashes with TypeError: unsupported operand type(s) for -: 'Nonetype' and 'float'.

**Comment by AdriaanRol** [comment]
👋 Who are you @Odrenal ?

**Comment by MiguelSMoreira** [comment]
This implementation of the resonator scan function already follows the expected behavior for the qubit object
