### ISSUE TITLE
Readout Optimization using GBT

### ISSUE THREAD

**Issue by jorgemfm27** [DiCarloLab-Delft/PycQED_py3#609]
Request feature for SSRO Readout calibration in GBT.

Proper RO calibration relies on Rabi pulse calibration.
Three different calibration steps are envisioned to do this calibration:
- Measuring dispersive shift.
- 2D of readout fidelity over the ro_pulse_amp and ro_freq_parameters
- Calibration of optimal integration weights near the highest fidelity.

**Comment by jorgemfm27** [comment]
Created dependency graph:
![Untitled](https://user-images.githubusercontent.com/32438956/72898862-2a3dd100-3d25-11ea-8484-3e7b79c9325b.png)

**Comment by jorgemfm27** [comment]
Introduced changes in CCL_transmon to accomodate for the Dispersive shift node and pushed them to feature cc.

Among these are:
- changes to the '<qubit>.measure_dispersive_shift_pulsed' function.
- new ccl_transmon parameter <qubit>.dispersive_shift

**Comment by jorgemfm27** [comment]
Tested 'Dispersive Shift' node on two qubits with success.

Moving to Acquisition delay calibration...

**Comment by jorgemfm27** [comment]
Readout acquisition delay is done.
The calibration can be performed using the CCL_Transmon function:
<qubit>.calibrate_ro_acq_delay()
Analysis is performed by:
readout_analysis.RO_acquisition_delayAnalysis

The routine has been tested on several qubits.
![I_axis_20200123_191321](https://user-images.githubusercontent.com/32438956/73058918-e669d980-3e94-11ea-823b-bb29a9e5eb72.png)
![Q_axis_20200123_191321](https://user-images.githubusercontent.com/32438956/73058921-e8339d00-3e94-11ea-863b-049cc9d284fc.png)

**Comment by AdriaanRol** [comment]
@jorgemfm27 , I'm curious how you automated this. Usually it is quite easy to do this analysis by hand and detect the edges. I am wondering how you make sure the parameters are updated automatically and correctly. 

There is a related issue relating to the pulse timings. This calibration performs the timing calibration of the  UHFQA pulse vs acquisition window. There are also the timings of all pulses with respect to each other. This is logged in the device object (see also issue #533 and related #536) the issue for having these protocols automated is #450.

**Comment by jorgemfm27** [comment]
Introduced changes in CCL transmon <qubit>.measure_dispersive_shift_pulsed.
Still need to perform proper plotting of data (current implementation stores data in two different experiments and plots each transmission trace individually).

Changes have been tested are are currently working in the Pagani setup.

**Comment by jorgemfm27** [comment]
GBT readout routine is completed.

**Comment by MiguelSMoreira** [comment]
Addressed according to @jorgemfm27 and tested on Ferrari
