### ISSUE TITLE
Soft Avg not working in spectroscopy

### ISSUE THREAD

**Issue by elrama-** [DiCarloLab-Delft/PycQED_py3#61]
I pulled the changes from PR #59 into 2Q_gates_branch (e953d78). Tried to use it for continuous resonator measurements, but stops after the first iteration. However, MC is prediting the time correctly, it is just exiting the loop prematurely.

**Comment by AdriaanRol** [comment]
@elrama- I have implemented soft averaging for hard-sweeps. I did not think of also implementing it for soft sweeps but I can see the use (fast spec scans and then repeating till the signal is clear sounds like a very pleasant way of working).
