### ISSUE TITLE
VSM channel amp BUG

### ISSUE THREAD

**Issue by hasali92** [DiCarloLab-Delft/PycQED_py3#610]
I found a bug in the VSM when driving Pipulse . 

 When driving a pi-pulse through D1 mw connected directly to to the output of the drive mixer seems to be so different from that connected to the VSM ch_mod. It seems we lose some SNR when connecting to VSM.  
 
The default value of this parameter vsm.mod1_chl_guassian_amp  is 1.0. However, when i changed it to 0.99 and back to 1.0,  Pi pulse amplitude using VSM gives the same value as connecting it directly to the drive mixer output. 

It seems there is a bug when setting the vsm.mod1_chl_guassian_amp to 1 by default, but we you change manually to any other value, back to 1, it works fine. 

The error is not reproducible. Once you change vsm.mod1_chl_guassian_amp, it seems to be working fine. 

### Steps to reproduce
1.
2.
3.

### Expected behaviour
One needs to set vsm.mod1_chl_guassian_amp to 1, not to lose SNR, thus a pi pulse can be driven in 20 ns. 

### Actual behaviour
However,  driving a pi-pulse through D1 mw connected directly to to the output of the drive mixer seems to be so different from that connected to the VSM ch_mod. It seems we lose some SNR when connecting to VSM.  
 
The default value of this parameter vsm.mod1_chl_guassian_amp  is 1.0. However, when i changed it to 0.99 and back to 1.0,  Pi pulse amplitude using VSM gives the same value as connecting it directly to the drive mixer output. 

It seems there is a bug when setting the vsm.mod1_chl_guassian_amp to 1 by default, but we you change manually to any other value, back to 1, it works fine. 

### System
**operating system**
window 7 

**PycQED branch**
develop 

**PycQED commit**

**Comment by AdriaanRol** [comment]
@hasali92 please document what you've found that explains what happened.

**Comment by MiguelSMoreira** [comment]
Should already be fixed.
Pending status update from @hasali92

**Comment by hasali92** [comment]
VSM is initialised in a float way. This means that all settings such as Gaussian_amp, attribute_averages or marker state will be floating, not the values you think they are.

This means that one needs to intentionally mention all the VSM parameters going to be used in the init script with the rights/default settings.
