### ISSUE TITLE
Analysis for dispersive shift node (GBT).

### ISSUE THREAD

**Issue by jorgemfm27** [DiCarloLab-Delft/PycQED_py3#611]
Introduce proper analysis for the function measure_dispersive_shift_pulsed.

**Comment by jorgemfm27** [comment]
Analysis is complete.
Find it in: "analysis_v2/readout_analysis/Dispersive_shift_Analysis"

example:
![Transmission_axis_20200204_145553](https://user-images.githubusercontent.com/32438956/73844182-5cb8f500-4820-11ea-95a5-32ead6523860.png)

**Comment by MiguelSMoreira** [comment]
Fixed according to @jorgemfm27
