### ISSUE TITLE
data path still not loading properly

### ISSUE THREAD

**Issue by elrama-** [DiCarloLab-Delft/PycQED_py3#62]
Whe pulling PR #59 into 2Q_gates_branch (e953d78), I realize the data-path is still wrongly assigned to the data folder within pycqed.

**Comment by AdriaanRol** [comment]
@elrama- , I have made a hotfix on the intel demo branch de55c12a88f8f67ee7a1629e1d9187086d59af38 which I you have pulled into the 2Q gates branch. Note that this is a workaround that solves the problem. 

However, this relates to a bigger issue the way we specify the datafolder in the init does not work. Instead we fall back to the setup dictionary which has hardcoded data directories in it. 
I will try to make a proper solution for this.
