### ISSUE TITLE
CI fails (again)

### ISSUE THREAD

**Issue by wvlothuizen** [DiCarloLab-Delft/PycQED_py3#640]
tagged last working commit as v0.3-rc1

**Comment by MiguelSMoreira** [comment]
Depending on whether or not the failing tests are part of the "Non-important" or "To be removed" tests described in issue #635, this can be easily addressed by just deprecating tests that are not passing, on par with the new lab policy towards the test suite

**Comment by wvlothuizen** [comment]
I'm currently fixing some CI failures related to the OpenQL version. Maybe first merge PR #620, then act according to issue #635 and repair anything important

**Comment by wvlothuizen** [comment]
CI was OK for some time, but started failing again with commit bd19f56 in PR #658. This is the summary:

- [ ] FAILED pycqed/tests/test_gst.py::Test_GST_CC::test_parser - AttributeError: m...
- [ ] FAILED pycqed/tests/test_pygsti_helpers.py::Test_pygsti_helpers::test_pygsti_expList_from_dataset
- [ ] FAILED pycqed/tests/test_pygsti_helpers.py::Test_pygsti_helpers::test_split_expList
- [ ] FAILED pycqed/tests/analysis_v2/test_cryoscope_analysis.py::Test_Cryoscope_analysis::test_Cryoscope_Analysis
- [ ] FAILED pycqed/tests/analysis_v2/test_cryoscope_analysis.py::Test_Cryoscope_analysis::test_RamZFluxArc
- [ ] FAILED pycqed/tests/analysis_v2/test_cryoscope_analysis.py::Test_Cryoscope_analysis::test_sliding_pulses_analysis
- [ ] FAILED pycqed/tests/dev_qubit_objs/test_device_objects.py::Test_Device_obj::test_prepare_timing_CC
- [ ] FAILED pycqed/tests/dev_qubit_objs/test_device_objects.py::Test_Device_obj::test_prepare_timing_CCL
- [ ] FAILED pycqed/tests/dev_qubit_objs/test_device_objects.py::Test_Device_obj::test_prepare_timing_QCC
- [ ] FAILED pycqed/tests/dev_qubit_objs/test_device_objects.py::Test_Device_obj::test_prepare_timing_QCC_fine
- [ ] FAILED pycqed/tests/instrument_drivers/meta_instrument/LutMans/test_mw_lutman.py::Test_MW_LutMan::test_render_wave
- [ ] FAILED pycqed/tests/instrument_drivers/meta_instrument/LutMans/test_mw_lutman.py::Test_MW_LutMan::test_render_wave_PSD
- [ ] FAILED pycqed/tests/instrument_drivers/meta_instrument/LutMans/test_mw_lutman.py::Test_MW_LutMan::test_uploading_standard_pulses
- [ ] FAILED pycqed/tests/instrument_drivers/meta_instrument/LutMans/test_mw_lutman.py::Test_MW_LutMan::test_uploading_standard_pulses_QWG_lutman
- [ ] FAILED pycqed/tests/openql/test_multi_qubit_oql.py::Test_multi_qubit_oql::test_Chevron
- [ ] FAILED pycqed/tests/openql/test_multi_qubit_oql.py::Test_multi_qubit_oql::test_Cryoscope
- [ ] FAILED pycqed/tests/openql/test_pygsti_oql.py::Test_pygsti_oql::test_poor_mans_2q_gst
- [ ] FAILED pycqed/tests/openql/test_pygsti_oql.py::Test_pygsti_oql::test_single_qubit_gst
- [ ] FAILED pycqed/tests/openql/test_pygsti_oql.py::Test_pygsti_oql::test_two_qubit_gst

= 19 failed, 354 passed, 78 skipped, 5 xfailed, 106 warnings in 700.15s (0:11:40) =
