### ISSUE TITLE
CBox Assembler does not check all syntax

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#65]
This leads to a situation where we think we have valid .asm files but in reality it does not run on the CBox.

**Comment by AdriaanRol** [comment]
@gtaifu I'll be adding examples here as I run accros them. 

- Setting  `wait 0` does not produce valid code but does not raise an error.

**Comment by AdriaanRol** [comment]
When debugging QuMIS with @gtaifu we ran into quite a few hard to find bugs in the auto generated code. It turns out there are some requirements to the QuMIS. 

It would be good to check against these upon compilation. 
Some of these include 
- [ ] Program should start with a `wait` instruction. 
- [ ] There should be a wait statement after a jump statement. 

@gtaifu , if there are any more constraints, could you add these to this list?

**Comment by AdriaanRol** [comment]
@gtaifu I think we can close this now right?

**Comment by gtaifu** [comment]
@AdriaanRol  

Not yet.  For example, the assembler still does not check is a wait instruction is inserted between a trigger/measure/pulse instruction and a label.

I will do it later. And then we could close this issue.

**Comment by wvlothuizen** [comment]
Closing because Cbox is old
