### ISSUE TITLE
Raise default ziDAQServer's logging level 

### ISSUE THREAD

**Issue by mariosk-zi** [DiCarloLab-Delft/PycQED_py3#663]
Currently `ziDAQServer`'s logging level is set to `0`. For reference the debug levels are:
```
trace = 0, debug, info, status, warning, error, fatal
```

Raise the default logging level to `status` (3), to avoid flooding the user with unnecessary messages, especially `trace` and `debug` messages.

**Comment by MiguelSMoreira** [comment]
I agree with this proposal. Let's make the default log level 3 (status) and either create new issues (or update this current issue) every time that new (and unwanted) log messages are found above the default level

**Comment by MiguelSMoreira** [comment]
The proposed changes to the default logging level of Zurich Instruments devices have been implemented. From now on, lower severity or irrelevant messages should be cataloged on a case-by-case basis, and addressed directly with the QuSurf team.
