### ISSUE TITLE
Proper test and installation instructions for CBox codec

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#68]
Highlighted by @elrama- trouble installing the CBox dependencies on Stefano's computer . 

Problem arises when it tries to import the C-codec for the CBox. The working of this can easily be tested independent of the CBox. Tests also already exist for this but need to be moved over to the test suite. 
By moving over the CBox compiler to the tests it is possible to find this out early on in the setup proces and link to the correct instructions. (problem of Ramiro is related to not having enough disk space to install microsoft visual studio). 

- [ ] Move over test for codec so failure will be spotted immediately in the install process.

**Comment by wvlothuizen** [comment]
Closing bacause CBox is old
