### ISSUE TITLE
CC timeout on measure_parity_check_flux_dance 

### ISSUE THREAD

**Issue by wvlothuizen** [DiCarloLab-Delft/PycQED_py3#698]
When running `HAL_Device::measure_parity_check_flux_dance`, a CC timeout occurs, depending on the value of parameter `flux_dance_steps`

**Comment by wvlothuizen** [comment]
A first analysis shows that the .vq1asm program for the CC is huge (>30 MB), and that the internal assembly process inside the CC takes ~12 s per CCIO (running in parallel).
Because most of the file consists of comments to assist debugging, a change was made to the CCCore driver to strip comments from the .vq1asm file before transmitting to the CC in order to reduce file size and thus processing time.

@hasali92 can you report here on the success of the change?

**Comment by hasali92** [comment]
Hi Wouter, thanks for creating the issue. The changes you made worked. Now, with weight-4 paritty check, i can run up to 7 repeated parity check codewords without any timeout error. I haven't tried more than 7 as 7 for me is enough, but i can do more if you want to see when it is going to fail.

**Comment by MiguelSMoreira** [comment]
Issue addressed
