### ISSUE TITLE
Fix qutechopenql build fail during CI

### ISSUE THREAD

**Issue by MiniSean** [DiCarloLab-Delft/PycQED_py3#718]
One (of many) steps to address CI failing (`develop` [33c8dbd](https://github.com/DiCarloLab-Delft/PycQED_py3/commit/33c8dbdb3375d8446bd19848f02e05ea68d69d13)).

- CI fails when installing qutechopenql version from source:
`pip install qutechopenql --verbose --verbose --verbose --no-index -f https://github.com/DiCarloLab-Delft/OpenQL/releases`
- Provided exception (more info see [here](https://github.com/DiCarloLab-Delft/PycQED_py3/actions/runs/3191388090/jobs/5207637628)):
`DistributionNotFound: No matching distribution found for qutechopenql`
- When running a downgraded version requirement of qutechopenql (0.10.0, PyPI available), the following runtime errors appear:
`RuntimeError: Internal compiler error: Error in JSON definition: key 'cc' not found on path 'instructions/_fluxdance_1', actual node contents '{"decomposition":{"into":"{ cz q[10],q[8] | cz q[9],q[12] }"},"duration":0,"prototype":[]}'` 
---
- [x] Answer why `qutechopenql >= 0.10.3` is a hard requirement?
- [x] Fix qutechopenql install from source release/latest.
or
- [ ] Fix internal compiler errors while working with qutechopenql 0.10.0.

**Comment by MiniSean** [comment]
Hi @wvlothuizen,
I would like to know why `qutechopenql >= 0.10.3` is a hard requirement for pycqed and if it is possible to get away with version 0.10.0?

**Comment by wvlothuizen** [comment]
0.10.0 on PyPi is the last official release that doesn't contain any recent updates to the CC backend. 
Development releases are done in this repository, and the interaction with requirements.txt is a bit flaky.

It may be possible to increase the frequency of official releases, since access to PyPi by the official development team has recently be regained.

**Comment by MiniSean** [comment]
Having an official release would certainly make the installation process more reliable.
But until then, I want to find a solution for installing from source during CI. Any suggestions? Who are the other other official development teams? Maybe I can see how they handle this issue.
