### ISSUE TITLE
Get error state from CBox

### ISSUE THREAD

**Issue by gtaifu** [DiCarloLab-Delft/PycQED_py3#73]
As discussed with Adriaan and Jacob, the following method used to indicate errors would be helpful:
- When CBox receives a command from PC (which does not read data), the FPGA will send two bytes back: checksum + EndofMessageHeader (EoM). This is the current state.
- We can change it to: If the CBox goes to some wrong state, when next command comes from PC, the FPGA will still send two bytes back, but the second byte could be different: checksum + ErrorStateEoM.
- In the **driver** side, when it receives an ErrorStateEoM instead of EoM, then if raise an error.
- The programmer could send the ReadVersion command to inquire the CBox state. One byte is added to indicate the possible errors, such as out of instructions in the processor, or the waiting queue has been empty.

A more delicate plan should be made to make this happen in a systematic way.

**Comment by AdriaanRol** [comment]
@gtaifu , I ran into this issue today. It turns out that in some situations the CBox cannot keep up with the instructions I program. I'm now using derivative techniques to find out what's wrong. 

Having this feature would really help pushing the qumis to its limits.

**Comment by AdriaanRol** [comment]
Closing this issue as several debugging options have been added since this issue was created.
