### ISSUE TITLE
Analysis to extract g1, g2, and V-ref from "Olli" chevrons 

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#83]
We require an automated analysis for extracting the coefficients from the experiment described in Saira et al. (fig 1c and 1d, PRL 2014). We currently do this by hand. 

Below are figures of some sample data. 

![swap-cp length_x_vs_y](https://cloud.githubusercontent.com/assets/6142932/21420607/eeb2bcea-c82e-11e6-9cb2-c69c4a9bc6a2.png )

![swap-cp length_x_vs_y](https://cloud.githubusercontent.com/assets/6142932/21420610/f2c65152-c82e-11e6-9c4a-f1eb0fa33661.png)

**Comment by MiguelSMoreira** [comment]
Closed due to inactivity
