### ISSUE TITLE
composite pulse for 5014 sequencer

### ISSUE THREAD

**Issue by elrama-** [DiCarloLab-Delft/PycQED_py3#91]
Operation that takes two "pulse" objects for the pulsar and combines them into a single "composite" pulse. 

Use case is to for example allow combining multiple parts of the CPhase gate (pulse and compensation part) or to make the RO pulses into a proper single pulse object (currently there is some hacky stuff going on there). 

Low priority as we ideally want to stop using the 5014. However, seeing that our lab is larger we might as well do it properly.

**Comment by AdriaanRol** [comment]
We are not actively using the 5014 anymore therefore marked as won't fix.
