### ISSUE TITLE
Proper UHFQC multiplexed readout integration 

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#94]
Currently multiplexed readout exists as examples in multiple notebooks. 
However there are a few issues that need to be resolved. 
- [ ] integration into pycqed qubit and qubit object 
- [ ] auto setting of weight functions and uploading IQ pulses to UHFQC was removed from the qubit object so as to not overwrite multiplexed pulses. 

Futhermore, I could not get the existing example to run out of the box on another setup. Resolving that is also something I will have to do (and a first step in clarifying this stuff).

**Comment by AdriaanRol** [comment]
related to #135

**Comment by AdriaanRol** [comment]
@brianzi 
N.B. thing we found today, the crosstalk matrix got stuck after changing the asinged channels/going back to a regular readout. 
We should ensure this is set properly in prepare readout scripts. 

Another thing that can go wrong is that correlation modes remain enabled for certain channels.

**Comment by AdriaanRol** [comment]
Important update: Currently multiplexed readout **Only works if you always use resonator combinations = [`[0,1], [0,1],[0,1]]`. 

We need to look into this but until a proper implementation is there this workaround works fine.

**Comment by wvlothuizen** [comment]
too old
